// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ApproverentalTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void approverental() {
    driver.get("http://192.168.160.62/");
    driver.manage().window().setSize(new Dimension(879, 648));
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("cr7@ua.pt");
    driver.findElement(By.id("password")).sendKeys("aP5Xh6vc87jX9MN");
    driver.findElement(By.cssSelector(".MuiButton-contained > .MuiButton-label")).click();
    assertThat(driver.switchTo().alert().getText(), is("Welcome to Renti, Cristiano Ronaldo"));
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButtonBase-root:nth-child(4) > .MuiButton-label"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".MuiButtonBase-root:nth-child(4) > .MuiButton-label")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButton-label > a"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".MuiButton-label > a")).click();
    driver.findElement(By.cssSelector(".MuiCardContent-root:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".MuiTypography-root:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".MuiCardActions-root:nth-child(1) .MuiButton-label")).click();
    assertThat(driver.switchTo().alert().getText(), is("Approved with success"));
    driver.findElement(By.linkText("Go back to rentals")).click();
    {
      WebElement element = driver.findElement(By.linkText("Go back to rentals"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiContainer-root > .MuiButtonBase-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
  }
}
